# Generated by Django 4.1.6 on 2023-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='to_do', max_length=100),
        ),
    ]
