# Generated by Django 4.1.6 on 2023-02-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='visto',
        ),
    ]
