# Generated by Django 4.1.6 on 2023-02-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_rename_seen_notification_visto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='visto',
            new_name='seen',
        ),
    ]
