version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CatBikes
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/sql/dump.sql:/docker-entrypoint-initdb.d/datadump.sql
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 8080:80
    networks:
      - backend

  drf:
    build: ./backend/drf
    container_name: drf
    command: sh -c '/app/wait-for-it.sh -t 0 db:3306 -- python ./manage.py runserver 0.0.0.0:8000'
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - backend
volumes:
  dbdata:


networks:
  backend:
